/**
 * Application-wide constants and configuration
 */

export const SITE_CONFIG = {
  name: "Kuyash Integrated Farm",
  tagline: "Farming for a future",
  description: "Cultivating a sustainable future through innovative agriculture and empowering rural communities.",
} as const;

export const STATS = [
  { value: "5000+", label: "Farmers Connected" },
  { value: "90%", label: "Yield Improvement" },
  { value: "50+", label: "Agriculture Experts" },
  { value: "98%", label: "Positive Impact" },
] as const;

export const SERVICES = [
  {
    id: 1,
    title: "Crop & Vegetable Production",
    description: "Growing premium-quality crops and fresh vegetables using sustainable farming methods.",
  },
  {
    id: 2,
    title: "Livestock & Poultry Farming",
    description: "Raising healthy cattle, sheep, and poultry with modern animal husbandry practices.",
  },
  {
    id: 3,
    title: "Fish Farming",
    description: "Sustainable aquaculture systems producing fresh, quality fish.",
  },
  {
    id: 4,
    title: "Palm Oil Production",
    description: "Cultivating oil palm plantations for high-quality palm oil production.",
  },
  {
    id: 5,
    title: "Food Processing & Packaging",
    description: "Processing and packaging farm products to deliver fresh, quality food to customers.",
  },
  {
    id: 6,
    title: "Agricultural E-Commerce",
    description: "Connecting farmers and consumers through innovative digital marketplace solutions.",
  },
] as const;

export const GOALS = [
  {
    id: 1,
    value: "2B",
    label: "Liters of water conserved annually through smart irrigation",
  },
  {
    id: 2,
    value: "2B",
    label: "Collaborate on policy 2 billion liters of water annually through efficient water-saving practices",
  },
  {
    id: 3,
    value: "100M",
    label: "People impacted through sustainable farming, supporting livelihoods globally",
  },
] as const;

export const NAV_LINKS = [
  { label: "Home", href: "#home" },
  { label: "Services", href: "#services" },
  { label: "Projects", href: "#projects" },
  { label: "About Us", href: "#about" },
  { label: "Blog", href: "#blog" },
] as const;

export const FARM_CATEGORIES = [
  {
    id: 1,
    name: "Vegetables",
    description: "Fresh, organic vegetables grown with sustainable farming practices.",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=2084",
    slug: "vegetables",
  },
  {
    id: 2,
    name: "Fruits",
    description: "Sweet, juicy fruits harvested at peak ripeness for maximum flavor.",
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?q=80&w=2070",
    slug: "fruits",
  },
  {
    id: 3,
    name: "Poultry",
    description: "Premium quality chicken and eggs from free-range, healthy birds.",
    image: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?q=80&w=2087",
    slug: "poultry",
  },
  {
    id: 4,
    name: "Dairy",
    description: "Fresh milk and dairy products from grass-fed, well-cared-for cattle.",
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?q=80&w=2065",
    slug: "dairy",
  },
  {
    id: 5,
    name: "Grains",
    description: "Wholesome grains and cereals cultivated using modern agricultural methods.",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?q=80&w=2074",
    slug: "grains",
  },
  {
    id: 6,
    name: "Fishery",
    description: "Fresh, sustainably farmed fish from our aquaculture systems.",
    image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?q=80&w=2070",
    slug: "fishery",
  },
] as const;

export const PRODUCTS = {
  vegetables: [
    {
      id: 1,
      name: "Organic Tomatoes",
      price: 7500,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?q=80&w=2070",
      description: "Fresh, vine-ripened organic tomatoes",
      inStock: true,
      rating: 4.8,
      category: "vegetables",
      stock: 150,
      lowStockThreshold: 20,
      reorderPoint: 50,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 6500 },
        { minQuantity: 50, pricePerUnit: 6000 },
      ],
    },
    {
      id: 2,
      name: "Fresh Carrots",
      price: 5500,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?q=80&w=2087",
      description: "Sweet, crunchy organic carrots",
      inStock: true,
      rating: 4.9,
      category: "vegetables",
      stock: 200,
      lowStockThreshold: 30,
      reorderPoint: 60,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 4800 },
        { minQuantity: 50, pricePerUnit: 4400 },
      ],
    },
    {
      id: 3,
      name: "Green Lettuce",
      price: 4500,
      unit: "per head",
      image: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?q=80&w=2070",
      description: "Crisp, fresh lettuce heads",
      inStock: true,
      rating: 4.7,
      category: "vegetables",
      stock: 120,
      lowStockThreshold: 25,
      reorderPoint: 50,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 4000 },
        { minQuantity: 50, pricePerUnit: 3600 },
      ],
    },
    {
      id: 4,
      name: "Bell Peppers",
      price: 9000,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?q=80&w=2084",
      description: "Colorful mixed bell peppers",
      inStock: true,
      rating: 4.6,
      category: "vegetables",
      stock: 80,
      lowStockThreshold: 15,
      reorderPoint: 40,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 7800 },
        { minQuantity: 50, pricePerUnit: 7200 },
      ],
    },
    {
      id: 5,
      name: "Cucumbers",
      price: 6000,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?q=80&w=2070",
      description: "Fresh, crispy cucumbers",
      inStock: true,
      rating: 4.8,
      category: "vegetables",
      stock: 180,
      lowStockThreshold: 25,
      reorderPoint: 50,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 5200 },
        { minQuantity: 50, pricePerUnit: 4800 },
      ],
    },
    {
      id: 6,
      name: "Spinach",
      price: 6500,
      unit: "per bunch",
      image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=2080",
      description: "Nutrient-rich organic spinach",
      inStock: true,
      rating: 4.7,
      category: "vegetables",
      stock: 90,
      lowStockThreshold: 20,
      reorderPoint: 45,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 5600 },
        { minQuantity: 50, pricePerUnit: 5200 },
      ],
    },
  ],
  fruits: [
    {
      id: 7,
      name: "Fresh Strawberries",
      price: 11000,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?q=80&w=2070",
      description: "Sweet, juicy strawberries",
      inStock: true,
      rating: 4.9,
      category: "fruits",
      stock: 60,
      lowStockThreshold: 10,
      reorderPoint: 30,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 9500 },
        { minQuantity: 50, pricePerUnit: 8800 },
      ],
    },
    {
      id: 8,
      name: "Organic Apples",
      price: 7500,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?q=80&w=2074",
      description: "Crisp, sweet apples",
      inStock: true,
      rating: 4.8,
      category: "fruits",
      stock: 250,
      lowStockThreshold: 40,
      reorderPoint: 80,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 6500 },
        { minQuantity: 50, pricePerUnit: 6000 },
      ],
    },
    {
      id: 9,
      name: "Bananas",
      price: 4500,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1603833665858-e61d17a86224?q=80&w=2054",
      description: "Ripe, fresh bananas",
      inStock: true,
      rating: 4.7,
      category: "fruits",
      stock: 300,
      lowStockThreshold: 50,
      reorderPoint: 100,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 4000 },
        { minQuantity: 50, pricePerUnit: 3600 },
      ],
    },
    {
      id: 10,
      name: "Oranges",
      price: 8500,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?q=80&w=2074",
      description: "Juicy, vitamin-rich oranges",
      inStock: true,
      rating: 4.8,
      category: "fruits",
      stock: 180,
      lowStockThreshold: 30,
      reorderPoint: 70,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 7400 },
        { minQuantity: 50, pricePerUnit: 6800 },
      ],
    },
  ],
  poultry: [
    {
      id: 11,
      name: "Free-Range Chicken",
      price: 20000,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=2070",
      description: "Premium free-range chicken",
      inStock: true,
      rating: 4.9,
      category: "poultry",
      stock: 75,
      lowStockThreshold: 10,
      reorderPoint: 30,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 17000 },
        { minQuantity: 50, pricePerUnit: 16000 },
      ],
    },
    {
      id: 12,
      name: "Fresh Eggs",
      price: 9500,
      unit: "per dozen",
      image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?q=80&w=2070",
      description: "Farm-fresh organic eggs",
      inStock: true,
      rating: 5.0,
      category: "poultry",
      stock: 150,
      lowStockThreshold: 30,
      reorderPoint: 60,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 8200 },
        { minQuantity: 50, pricePerUnit: 7600 },
      ],
    },
  ],
  dairy: [
    {
      id: 13,
      name: "Fresh Milk",
      price: 6000,
      unit: "per liter",
      image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=2087",
      description: "Pure, fresh farm milk",
      inStock: true,
      rating: 4.8,
      category: "dairy",
      stock: 200,
      lowStockThreshold: 40,
      reorderPoint: 80,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 5200 },
        { minQuantity: 50, pricePerUnit: 4800 },
      ],
    },
    {
      id: 14,
      name: "Organic Cheese",
      price: 14000,
      unit: "per 500g",
      image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?q=80&w=2073",
      description: "Artisan farm cheese",
      inStock: true,
      rating: 4.9,
      category: "dairy",
      stock: 45,
      lowStockThreshold: 8,
      reorderPoint: 20,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 12000 },
        { minQuantity: 50, pricePerUnit: 11200 },
      ],
    },
  ],
  grains: [
    {
      id: 15,
      name: "Brown Rice",
      price: 7000,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=2070",
      description: "Wholesome brown rice",
      inStock: true,
      rating: 4.7,
      category: "grains",
      stock: 500,
      lowStockThreshold: 80,
      reorderPoint: 150,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 6100 },
        { minQuantity: 50, pricePerUnit: 5600 },
      ],
    },
    {
      id: 16,
      name: "Organic Wheat",
      price: 6000,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?q=80&w=2074",
      description: "Premium quality wheat",
      inStock: true,
      rating: 4.8,
      category: "grains",
      stock: 600,
      lowStockThreshold: 100,
      reorderPoint: 200,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 5200 },
        { minQuantity: 50, pricePerUnit: 4800 },
      ],
    },
  ],
  fishery: [
    {
      id: 17,
      name: "Fresh Tilapia",
      price: 17000,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?q=80&w=2074",
      description: "Farm-raised fresh tilapia",
      inStock: true,
      rating: 4.8,
      category: "fishery",
      stock: 100,
      lowStockThreshold: 15,
      reorderPoint: 40,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 14800 },
        { minQuantity: 50, pricePerUnit: 13600 },
      ],
    },
    {
      id: 18,
      name: "Catfish",
      price: 15500,
      unit: "per kg",
      image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?q=80&w=2070",
      description: "Sustainably farmed catfish",
      inStock: true,
      rating: 4.7,
      category: "fishery",
      stock: 120,
      lowStockThreshold: 20,
      reorderPoint: 50,
      lastRestocked: new Date().toISOString(),
      bulkPricing: [
        { minQuantity: 10, pricePerUnit: 13500 },
        { minQuantity: 50, pricePerUnit: 12400 },
      ],
    },
  ],
} as const;

export const FOOTER_LINKS = {
  product: [
    { label: "Features", href: "#" },
    { label: "Pricing", href: "#" },
    { label: "Case Studies", href: "#" },
    { label: "Reviews", href: "#" },
  ],
  company: [
    { label: "About", href: "#" },
    { label: "Team", href: "#" },
    { label: "Careers", href: "#" },
    { label: "Contact", href: "#" },
  ],
  services: [
    { label: "Soil Enrichment", href: "#" },
    { label: "Water Management", href: "#" },
    { label: "Crop Consultation", href: "#" },
    { label: "Organic Farming", href: "#" },
  ],
  innovations: [
    { label: "Smart Irrigation", href: "#" },
    { label: "Precision Agriculture", href: "#" },
    { label: "Sustainable Practices", href: "#" },
    { label: "AI Solutions", href: "#" },
  ],
  successStories: [
    { label: "Farmer Testimonials", href: "#" },
    { label: "Community Impact", href: "#" },
    { label: "Case Studies", href: "#" },
    { label: "Research Papers", href: "#" },
  ],
} as const;
